In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train=pd.read_excel("E:/Datasets/PredictTheNews/Data_Train.xlsx")

In [3]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [4]:
df_train.head()

STORY  SECTION
0  But the most painful was the huge reversal in ...        3
1  How formidable is the opposition alliance amon...        0
2  Most Asian currencies were trading lower today...        3
3  If you want to answer any question, click on ‘...        1
4  In global markets, gold prices edged up today ...        3

In [6]:
nltk.download('stopwords') #downloading the stopwords from nltk
corpus = [] # List for storing cleaned data
ps = PorterStemmer() #Initializing object for stemming
for i in range(len(df_train)): # for each obervation in the dataset
   #Removing special characters
   text = re.sub('[^a-zA-Z]', ' ', df_train['STORY'][i]).lower().split()
   #Stemming and removing stop words
   text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
   #Joining all the cleaned words to form a sentence
   text = ' '.join(text)
   #Adding the cleaned sentence to a list
   corpus.append(text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mayank\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [12]:
cv = CountVectorizer(max_features = 120)
X = cv.fit_transform(corpus).toarray()
y = df_train.iloc[:, 1].values

In [24]:
df_test=pd.read_excel("E:/Datasets/PredictTheNews/Data_Test.xlsx")

In [27]:
nltk.download('stopwords') #downloading the stopwords from nltk
corpus1 = [] # List for storing cleaned data
ps = PorterStemmer() #Initializing object for stemming
for i in range(len(df_test)): # for each obervation in the dataset
   #Removing special characters
   text = re.sub('[^a-zA-Z]', ' ', df_test['STORY'][i]).lower().split()
   #Stemming and removing stop words
   text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
   #Joining all the cleaned words to form a sentence
   text = ' '.join(text)
   #Adding the cleaned sentence to a list
   corpus1.append(text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mayank\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [29]:
x_test=cv.fit_transform(corpus1).toarray()

In [30]:
x_test

array([[0, 0, 0, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [23]:
corpus

['pain huge revers fee incom unheard among privat sector lender essenti mean ye bank took grant fee structur loan deal paid account upfront book borrow turn default fee tie loan deal fell crack gill vow shift safer account practic amort fee incom rather book upfront gill move mend past way mean nasti surpris futur good news consid investor love clean imag loath uncertainti gain without pain promis strong stabl balanc sheet come sacrific well investor give hope phenomen growth promis made kapoor',
 'formid opposit allianc among congress jharkhand mukti morcha jmm jharkhand vika morcha prajatantrik',
 'asian currenc trade lower today south korean china renminbi china offshor malaysian ringgit indonesian rupiah taiwan dollar howev japanes yen dollar index measur us currenc strength major currenc trade previou close',
 'want answer question click answer click answer also check repli user proceed answer either write voic command want ask question click ask question question prefix alreadi i

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [16]:
classifier = SVC()
classifier.fit(X_train, y_train)

C:\Users\Mayank\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [31]:
y_predict = classifier.predict(x_test)

In [18]:
def accuracy(confusion_matrix):
   diagonal_sum = confusion_matrix.trace()
   sum_of_all_elements = confusion_matrix.sum()
   return diagonal_sum / sum_of_all_elements

In [20]:
cm = confusion_matrix(y_val, y_pred)

In [21]:
print("Accuracy : ", accuracy(cm))

Accuracy :  0.8813892529488859


In [22]:
X_val

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 3, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 2, 2],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
y_predict

array([0, 2, 0, ..., 0, 1, 1], dtype=int64)

In [34]:
submission = pd.DataFrame({
        "SECTION": y_predict
    })
submission.to_csv('submission_news.csv', encoding='utf-8', index=False)